services:
  - type: web
    name: notes-api
    runtime: node
    plan: free
    region: oregon  # Or choose: ohio / frankfurt / singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000  # Or omit if your app listens on process.env.PORT
    autoDeploy: true
    rootDir: .  # Adjust if your project is in a subfolder
